package com.samplesoap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.7.fuse-sb2-740008
 * 2019-06-08T19:07:16.925+05:30
 * Generated source version: 3.2.7.fuse-sb2-740008
 *
 */
@WebService(targetNamespace = "http://SampleSOAP.com", name = "SOATestEndpoint")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SOATestEndpoint {

    @WebMethod(operationName = "SOATest", action = "http://SampleSOAP.com")
    @WebResult(name = "outputSOATest", targetNamespace = "http://SampleSOAP.com", partName = "out")
    public OutputSOATest soaTest(
        @WebParam(partName = "in", name = "inputSOATest", targetNamespace = "http://SampleSOAP.com")
        InputSOATest in
    );
}
